{
 "title": "AWS RDS — Relational Database",
 "tags": [
  "aws",
  "rds",
  "cloudwatch"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "rds_instance",
    "label": "RDS Instance",
    "query": {}
   },
   { "name": "period", "label": "Period", "query": "60,120,300,900,3600" }
  ]
 },
 "panels": [
  { "title": "━━━━━  RDS  ▸  Status  ━━━━━", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  Key Health Indicators  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Read Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Replica Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  { "title": "━━━━━  RDS  ▸  Overview  ━━━━━", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  CPU & Memory  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU %",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "CPU Credit Balance",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Memory & Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Freeable Memory",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Swap Usage",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  Storage & I/O  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Free Storage",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "Read IOPS",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write IOPS",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  Latency & Throughput  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Read / Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Read Latency",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write Latency",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read / Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Read Throughput",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write Throughput",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  Connections & Network  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Connections",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Receive",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Transmit",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "━━━━━  RDS  ▸  Replication & Queue  ━━━━━",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Replica Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Replica Lag",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Queue Depth",
     "dimensions": { "DBInstanceIdentifier": "$rds_instance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}